image: node:latest

stages:
  - build

build-app:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn run build
    - mkdir -p ./public
    - cp -r ./dist/* ./public
    - tar -cf - dist | gzip > dist.gz
  artifacts:
      paths:
      - dist.gz
      - public