image: node:latest

stages:
  - build
  - pages

build-app:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn run build
    - tar -cf - dist | gzip > dist.gz
  artifacts:
      paths:
      - dist.gz

pages:
  stage: pages
  before_script:
    - yarn install
  script:
    - yarn run build
    - mkdir -p ./public
    - cp -r ./dist/* ./public
  artifacts:
    paths:
    - public