image: node:latest

stages:
  - build

pages:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn run build
    - mkdir -p ./public
    - cp -r ./dist/* ./public
    - tar -cf - dist | gzip > dist.gz
  artifacts:
    paths:
    - public
    - dist.gz